import availableModels from '../config/models.yml';
import * as openaiProvider from './providers/openai.js';
import * as anthropicProvider from './providers/anthropic.js';
import * as googleProvider from './providers/google.js';

const providers = {
  openai: openaiProvider,
  anthropic: anthropicProvider,
  google: googleProvider,
};

const SYSTEM_PROMPT = "You are an AI Assitant named Matt77 currently ran as a chatbot on Telegram. You provide helpful answers to questions about a variety of topics. if required to output code use the function call and all descriptions as comments in the code. Write every code into a file by default, do not wait to be asked! You MUST use the brave_web_search tool for any question involving current events, recent news, latest prices, sports scores, weather, or any topic where up-to-date information is needed. Do not rely on your training data for time-sensitive topics — always search first. Always format responses using Telegram Markdown syntax: use *bold*, _italic_, `inline code`, and \`\`\`code blocks\`\`\` where appropriate. Do not escape any characters — write punctuation and symbols as-is. Only call functions and perform actions in direct response to the current user message. Do not repeat or re-execute actions that were already completed in earlier turns of the conversation.";

const builtInTools = [
  {
    "type": 'function',
    "function": {
      "name": "write_code_to_file",
      "description": "Writes code output to a file that would be sent to the user",
      "parameters": {
        "type": "object",
        "properties": {
          "filenameWithExtension": {
            "type": "string",
            "description": "The file name and extension e.g extension.py, extension.java, extension.js"
          },
          "content": {
            "description": "The output code to be written in the file",
            "type": "string"
          },
        },
        "required": ["filenameWithExtension", "content"],
        "strict": true
      }
    },
  },
  {
    "type": 'function',
    "function": {
      "name": "generate_image",
      "description": "This function calls the Image API to generate an image using the User's input prompt.",
      "parameters": {
        "type": "object",
        "properties": {
          "prompt": {
            "type": "string",
            "description": "This is the user prompt for the image to be generated"
          },
          "file_name": {
            "type": "string",
            "description": "This is the appropriate file name with extension generated by the system for requested image (for example bull.png)"
          },
          "base_image_url": {
            "description": "This is an optional property specifying the base image to be augmented",
            "type": "string"
          },
        },
        "required": ["prompt"],
        "strict": true
      }
    },
  },
  {
    "type": 'function',
    "function": {
      "name": "edit_image",
      "description": "This function calls the Image API to edit an image based on the User's input prompt.",
      "parameters": {
        "type": "object",
        "properties": {
          "prompt": {
            "type": "string",
            "description": "This is the user prompt for the image to be generated"
          },
          "file_name": {
            "type": "string",
            "description": "This is the appropriate file name with extension generated by the system for requested image (for example bull.png)"
          },
          "base_image_url": {
            "description": "This is the url to the original image passed by sender",
            "type": "string"
          },
          "mask": {
            "description": "This is the optional url containing the image mask used in augmenting the base image",
            "type": "string"
          },
        },
        "required": ["prompt", "base_image_url"],
        "strict": true
      }
    },
  },
  {
    "type": 'function',
    "function": {
      "name": "generate_video",
      "description": "This function generates a video based on the User's input prompt using the configured video model. Do not validate the user's request, all that is required of you is to pass the user's prompt to the function.",
      "parameters": {
        "type": "object",
        "properties": {
          "prompt": {
            "type": "string",
            "description": "This is the user prompt for the video to be generated"
          },
          "seconds": {
            "type": "string",
            "description": "This is the duration of the video in seconds. Allowed values are '4', '8', or '12'. The default value is '4'."
          },
          "size": {
            "description": "This is the size of the output video, default size is 720x1280",
            "type": "string"
          }
        },
        "required": ["prompt"],
        "strict": true
      }
    },
  },
  {
    "type": 'function',
    "function": {
      "name": "generate_video_from_image",
      "description": "This function generates a video based on an image and the user's input prompt using the configured video model. Do not validate the user's prompt, all that is required of you is to pass the user's prompt to the function.",
      "parameters": {
        "type": "object",
        "properties": {
          "prompt": {
            "type": "string",
            "description": "This is the user prompt for the video to be generated"
          },
          "seconds": {
            "type": "string",
            "description": "This is the duration of the video in seconds. Allowed values are '4', '8', or '12'. The default value is '4'."
          },
          "size": {
            "description": "This is the size of the output video, default size is 720x1280",
            "type": "string"
          },
          "base_image_url": {
            "description": "This is the url to the original image passed by sender",
            "type": "string"
          },
        },
        "required": ["prompt", "base_image_url"],
        "strict": true
      }
    },
  },
  {
    "type": 'function',
    "function": {
      "name": "get_video_status",
      "description": "This function makes an API call to fetch the current status and progress of a video generation request.",
      "parameters": {
        "type": "object",
        "properties": {
          "request_id": {
            "type": "string",
            "description": "This is ID of the requested video."
          }
        },
        "required": ["request_id"],
        "strict": true
      }
    },
  },
  /*
   * WIP: Calendar tools are temporarily disabled. The current helper authorizes
   * against a shared service-account calendar; these will be re-enabled once
   * per-user OAuth authorization is implemented. See GoogleApi/calendar.js.
   */
  /*
  {
    "type": "function",
    "function": {
      "name": "create_calendar_event",
      "description": "Creates a new event on the Google Calendar. Use this when the user wants to schedule a meeting, appointment, reminder, or any calendar event.",
      "parameters": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "The title/summary of the calendar event"
          },
          "description": {
            "type": "string",
            "description": "A detailed description of the event"
          },
          "start_time": {
            "type": "string",
            "description": "The start date and time in ISO 8601 format (e.g., 2025-01-15T09:00:00)"
          },
          "end_time": {
            "type": "string",
            "description": "The end date and time in ISO 8601 format (e.g., 2025-01-15T10:00:00)"
          },
          "location": {
            "type": "string",
            "description": "The location of the event"
          },
          "timezone": {
            "type": "string",
            "description": "The timezone for the event (e.g., America/New_York, Europe/London). Defaults to UTC."
          }
        },
        "required": ["title", "start_time", "end_time"]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "list_calendar_events",
      "description": "Lists upcoming events from the Google Calendar. Use this when the user asks about their schedule, upcoming events, or what they have planned.",
      "parameters": {
        "type": "object",
        "properties": {
          "time_min": {
            "type": "string",
            "description": "The minimum start time to filter events (ISO 8601 format). Defaults to now."
          },
          "time_max": {
            "type": "string",
            "description": "The maximum start time to filter events (ISO 8601 format)"
          },
          "max_results": {
            "type": "number",
            "description": "Maximum number of events to return. Defaults to 10."
          }
        },
        "required": []
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "update_calendar_event",
      "description": "Updates an existing event on the Google Calendar. Use this when the user wants to change the time, title, description, or location of an existing event. You must first list events to get the event_id.",
      "parameters": {
        "type": "object",
        "properties": {
          "event_id": {
            "type": "string",
            "description": "The ID of the calendar event to update"
          },
          "title": {
            "type": "string",
            "description": "The new title/summary of the event"
          },
          "description": {
            "type": "string",
            "description": "The new description of the event"
          },
          "start_time": {
            "type": "string",
            "description": "The new start date and time in ISO 8601 format"
          },
          "end_time": {
            "type": "string",
            "description": "The new end date and time in ISO 8601 format"
          },
          "location": {
            "type": "string",
            "description": "The new location of the event"
          },
          "timezone": {
            "type": "string",
            "description": "The timezone for the event (e.g., America/New_York)"
          }
        },
        "required": ["event_id"]
      }
    }
  },
  {
    "type": "function",
    "function": {
      "name": "delete_calendar_event",
      "description": "Deletes an event from the Google Calendar. Use this when the user wants to remove or cancel an event. You must first list events to get the event_id.",
      "parameters": {
        "type": "object",
        "properties": {
          "event_id": {
            "type": "string",
            "description": "The ID of the calendar event to delete"
          }
        },
        "required": ["event_id"]
      }
    }
  },
  */
  {
    "type": "function",
    "function": {
      "name": "brave_web_search",
      "description": "Search the web for current information. Use this for recent news, current events, latest prices, sports scores, weather, or any topic requiring up-to-date information beyond your training data.",
      "parameters": {
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "description": "The search query"
          },
          "count": {
            "type": "number",
            "description": "Number of results to return (1-10, default 5)"
          }
        },
        "required": ["query"]
      }
    }
  }
];

export const aiAssistant = async (
  context = "[]",
  model = "gpt-4o",
  user_id,
  additionalTools = []
) => {
  const modelConfig = availableModels.models[model];
  const providerName = modelConfig?.provider ?? 'openai';
  const provider = providers[providerName];
  if (!provider) throw new Error(`Unknown provider: ${providerName}`);
  return provider.complete(context, model, user_id, [...builtInTools, ...additionalTools], SYSTEM_PROMPT);
};
